import './globals.css'
import type { Metadata } from 'next'
import  localFont  from 'next/font/local'

const dinNext = localFont({src:'../assets/fonts/dinnext.ttf'}) 

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" dir='rtl'>
      <body className={`${dinNext.className} text-base`}>{children}</body>
    </html>
  )
}
